version: "3.9"
services:
  security_ms:
    build:
      dockerfile: Dockerfile
      context: .
    command: run
    environment:
      - ENV=local
    ports:
      - "50055:50055"
    restart: unless-stopped

  security_redis:
    image: redis:6-alpine
    ports:
      - '127.0.0.1:35006:6379'
    volumes:
      - redis:/var/lib/redis
    restart: unless-stopped

volumes:
  redis:
    driver: local

networks:
  default:
    name: wrsnet
