version: "3.9"
services:
  security_ms_test:
    build:
      dockerfile: Dockerfile.test
      context: .
    depends_on:
      - security_redis_test
    environment:
      - ENV=test

  security_redis_test:
    image: redis:6-alpine
    ports:
      - '127.0.0.1:35006:6379'
    volumes:
      - redis:/var/lib/redis
    restart: unless-stopped

volumes:
  redis:
    driver: local

networks:
  default:
    name: wrsnet
